version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.pyasco:/root/.pyasco
    env_file: .env
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    command: uv run -m pyasco.app.telegram_bot --config /app/config.yml --telegram-token ${TELEGRAM_BOT_TOKEN}
