[build-system]
requires = ["hatchling", "uv"]
build-backend = "hatchling.build"

[project]
name = "pyasco"
version = "0.1.1"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ipython>=8.30.0",
    "jupyter-client>=8.6.3",
    "openai>=1.57.0",
    "pytest>=8.3.4",
    "tree-sitter-languages>=1.10.2",
    "tree-sitter==0.21.3",
    "ipykernel>=6.29.5",
    "rich>=13.9.4",
    "docker>=7.1.0",
    "numpy>=2.2.0",
    "prompt-toolkit>=3.0.48",
    "pyyaml>=6.0.2",
    "psutil>=6.1.0",
    "python-telegram-bot>=21.9",
    "scikit-learn>=1.6.1",
    "lancedb>=0.19.0",
    "tantivy>=0.22.0",
    "pandas>=2.2.3",
    "duckdb>=1.2.0",
    "pyaudio>=0.2.14",
    "deepgram-sdk>=3.10.0",
    "python-dotenv>=1.0.1",
    "pyttsx3>=2.98",
]

[project.scripts]
pyco = "pyasco.app.console:main"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["pyasco"]
